/*
 * Config.h
 *
 *  Created on: 27-Jun-2024
 *      Author: acer
 */

#ifndef MAIN_CONFIG_H_
#define MAIN_CONFIG_H_

#define BLE_TASK_STACK_DEPTH (30*1024)
#define BLE_SUBTASK_STACK_DEPTH (16*1024)
#define BLE_READ_WIFI_SCAN_LIST_STACK_DEPTH (4*1024)
#define BLE_READ_SYNC_PROP_STACK_DEPTH (4*1024)
#define CONSOLE_TASK_STACK_DEPTH (20*1024)
#define CONSOLE_INIT_TASK_STACK_DEPTH (50*1024)
#define CONSOLE_DEV_INFO_TASK_STACK_DEPTH (40*1024)
//#define ETH_TASK_STACK_DEPTH (15*1024)
#define EVENT_TASK_STACK_DEPTH (50*1024)
#define EVENT_CHECK_TASK_STACK_DEPTH (50*1024)
#define EVENT_EXECUTE_TASK_STACK_DEPTH (50*1024)
#define UPDATE_SCH_TABLE_TASK_STACK_DEPTH (20*1024)
#define UPDATE_ACT_TABLE_TASK_STACK_DEPTH (100*1024)
#define FILE_MANAGER_TASK_STACK_DEPTH (12*1024)   //20
#define FILE_MANAGER_WRITE_TASK_STACK_DEPTH (12*1024) //15
#define FILE_MANAGER_AUDIT_TEST_TASK_STACK_DEPTH (10*1024)   //20
#define FM_READ_LOG_DATA_TASK_STACK_DEPTH (4*1024)
#define FILE_SYSTEM_TASK_STACK_DEPTH (10*1024)
#define HTTP_TASK_STACK_DEPTH (25*1024)
#define HTTP_FETCH_TASK_STACK_DEPTH (30*1024)
#define HTTP_FILE_TASK_STACK_DEPTH (16*1024)
#define HTTP_POST_TASK_STACK_DEPTH (50*1024)
#define IDLE_TASK_STACK_DEPTH (15*1024)
#define IHUB_TASK_STACK_DEPTH (50*1024)
#define IHUB_GET_DEVICE_INFO_TASK_STACK_DEPTH (10*1024)
#define IHUB_WDT_TASK_STACK_DEPTH (10*1024)
#define LED_TASK_STACK_DEPTH (15*1024) //10
#define LED_MONITOR_CHASE_STACK_DEPTH (2*1024)
#define LED_MONITOR_BLINK_STACK_DEPTH (2*1024)
#define LED_UPDATE_BLINKSTATE_STACK_DEPTH (10*1024)
#define CHECK_INPUT_STACK_DEPTH (10*1024)
#define NTP_TASK_STACK_DEPTH (15*1024)
#define NTP_CONNECT_TASK_STACK_DEPTH (10*1024)
#define NTP_SYNC_CHECK_TASK_STACK_DEPTH (10*1024)
#define PBUTTON_TASK_STACK_DEPTH (15*1024)
#define PB_MON_UPDATE_TASK_STACK_DEPTH (16*1024)
#define PB_MON_POLL_TASK_STACK_DEPTH (16*1024)
#define SMTP_TASK_STACK_DEPTH (20*1024)
#define SMTP_SENDMAIL_TASK_STACK_DEPTH (15*1024)
#define LED_SETSTATE_TASK_STACK_DEPTH (15*1024)   //8
#define SMTP_SENDFILE_TASK_STACK_DEPTH (16*1024)
#define SPIFFS_MONITOR_TASK_STACK_DEPTH (10*1024)
#define SQL_TASK_STACK_DEPTH (20*1024)	//(20*1024)
#define SYSTEM_TASK_STACK_DEPTH (40*1024)
#define SRV_CONN_TASK_STACK_DEPTH (40*1024)
#define MON_SERVER_TASK_STACK_DEPTH (40*1024)
#define READ_PROPERTIES_SPIFFS_TASK_STACK_DEPTH (30*1024)
#define POST_FILE_ACK_TASK_STACK_DEPTH (16*1024)
#define SYSTEM_STATE_TASK_STACK_DEPTH (30*1024)
#define SYSTEM_TIMER_TASK_STACK_DEPTH (30*1024)
#define Auto_Execute_TASK_STACK_DEPTH (100*1024)
#define DA_TASK_STACK_DEPTH (15*1024)
#define POST_REC_LOG_SERVER_STACK_DEPTH (5*1024)
#define POST_DEBUG_LOG_SERVER_STACK_DEPTH (7*1024)
#define SEND_RECORDLOG_SERVER_STACK_DEPTH (8*1024)
#define GET_RECORD_SYNCSTATUS_STACK_DEPTH (16*1024)
#define DB_SYNC_CHECK_TASK_STACK_DEPTH (7*1024)
#define TCP_TASK_STACK_DEPTH (16*1024)
#define TCP_SOCKET1_TASK_STACK_DEPTH (6*1024)
#define TCP_SOCKET2_TASK_STACK_DEPTH (6*1024)
#define TCP_SOCKET3_TASK_STACK_DEPTH (6*1024)
#define TCP_SOCKET4_TASK_STACK_DEPTH (6*1024)
#define TRIM_TASK_STACK_DEPTH 		(50*1024)
#define TRIM_SUBTASK_STACK_DEPTH 	(50*1024)	//(100*1024)
#define UART_TASK_STACK_DEPTH (15*1024)
#define UART0_EVENT_TASK_STACK_DEPTH (10*1024)
#define UDP_TASK_STACK_DEPTH (16*1024)
#define UDP_SOCKET_TASK_STACK_DEPTH (10*1024)
#define WEBSERVER_TASK_STACK_DEPTH (10*1024)
#define START_WEBSERVER_TASK_STACK_DEPTH (10*1024)
#define WIFI_TASK_STACK_DEPTH (50*1024)
#define WIFI_NETWORKSCAN_TASK_STACK_DEPTH (10*1024)
#define WIFI_SCANTASK_STACK_DEPTH (20*1024)

#define BLEA_RD_SYS_PROP_TASK_STACK_DEPTH	(16*1024)
#define BLEA_RD_WIFI_SCANLIST_TASK_STACK_DEPTH	(4*1024)
#define CONSOLE_MSG_DBG_TASK_STACK_DEPTH	(30*1024)
#define COA_PROC_UART_MON_TASK_STACK_DEPTH	(4*1024)
#define COA_UART_EVENT_TASK_STACK_DEPTH	(4*1024)
#define COA_JFS_READ_FOTA_TASK_STACK_DEPTH	(10*1024)
#define COUA_PROC_UART_MON_TASK_STACK_DEPTH	(4*1024)
#define COUA_UART2_EVENT_TASK_STACK_DEPTH	(4*1024)
#define COUA_JFS_READ_FOTA_TASK_STACK_DEPTH	(10*1024)
#define EA_MON_TASK_STACK_DEPTH	(4*1024)
#define FMA_JFSSMTP_READ_TASK_STACK_DEPTH	(30*1024)
#define FMA_SDSMTP_READ_TASK_STACK_DEPTH	(10*1024)
#define FMA_RD_LOG_DATA_TASK_STACK_DEPTH	(4*1024)
#define TWIN_COMMAND_PROCESS_STACK_DEPTH   (30*1024)

//#define FS_MON_TASK_STACK_DEPTH	(4*1024)
//#define HA_HTTP_STR_READER_TASK_STACK_DEPTH	(12*1024)
//#define HAQI4T_MON_TASK_STACK_DEPTH	(6*1024)
//#define HAQI4T_GET_KEY_TASK_STACK_DEPTH	(15*1024)
//#define HAQI4T_HTTP_STR_READER_TASK_STACK_DEPTH	(5*1024)
#define IA_STATS_TASK_STACK_DEPTH	(4*1024)
#define IV1_POLL_DATA_TASK_STACK_DEPTH	(4*1024)
#define I_POLL_DATA_TASK_STACK_DEPTH	(4*1024)
#define JFSFA_OTAJFS_TASK_STACK_DEPTH	(10*1024)
#define RFSA_MON_TASK_STACK_DEPTH	(10*1024)
#define TCPAC_MON_TASK_STACK_DEPTH	(4*1024)
#define TCPAC_ClientListen_TASK_STACK_DEPTH	(4*1024)
#define DIRECT_METHOD_TASK_STACK_DEPTH	(10*1024)
//#define TRIM_TASK_STACK_DEPTH 		(16*1024)
//#define TRIM_SUBTASK_STACK_DEPTH 	(32*1024)
#define READ_COLOR_TABLE_TASK_STACK_DEPTH (100*1024)
#define READ_VIRTUAL_TABLE_TASK_STACK_DEPTH (20*1024)
#define READ_COMMAND_TABLE_TASK_STACK_DEPTH (80*1024)
#define READ_PLAYLIST_TABLE_TASK_STACK_DEPTH (80*1024)
#define ETH_TASK_STACK_DEPTH (100*1024)    //15
#define FMA_CPY_ALLFILES_TASK_STACK_DEPTH (30*1024)
// Define task stack size and priority
#define WATCHDOG_TASK_STACK_SIZE (1024 * 15)

#define TWIN_COMMAND_PROCESS_PRIORITY   2
#define DIRECT_METHOD_TASK_PRIORITY    2
#define BLEA_RD_SYS_PROP_TASK_PRIORITY    2
#define BLEA_RD_WIFI_SCANLIST_TASK_PRIORITY   2
#define CONSOLE_DEV_INFO_TASK_PRIORITY 2
#define CONSOLE_MSG_DBG_TASK_PRIORITY  1
#define COA_PROC_UART_MON_TASK_PRIORITY  5
#define COA_UART_EVENT_TASK_PRIORITY    2
#define COA_JFS_READ_FOTA_TASK_PRIORITY  5
#define COUA_PROC_UART_MON_TASK_PRIORITY  5
#define COUA_UART2_EVENT_TASK_PRIORITY  2
#define COUA_JFS_READ_FOTA_TASK_PRIORITY  5
#define EA_MON_TASK_PRIORITY   2
#define FILE_MANAGER_TASK_PRIORITY 8  //2
#define FILE_MANAGER_AUDIT_TEST_TASK_PRIORITY 5  //2
#define FM_READ_LOG_DATA_TASK_PRIORITY 2
#define FMA_JFSSMTP_READ_TASK_PRIORITY 2
#define FMA_SDSMTP_READ_TASK_PRIORITY   2
#define FMA_RD_LOG_DATA_TASK_PRIORITY   2
#define FS_MON_TASK_PRIORITY    2
#define HTTP_POST_TASK_PRIORITY 2
#define HA_HTTP_STR_READER_TASK_PRIORITY 5
#define HAQI4T_MON_TASK_PRIORITY  2
#define HAQI4T_GET_KEY_TASK_PRIORITY 2
#define HAQI4T_HTTP_STR_READER_TASK_PRIORITY 5
//#define IA_STATS_TASK_PRIORITY   2
#define IV1_POLL_DATA_TASK_PRIORITY 5
#define I_POLL_DATA_TASK_PRIORITY   5
#define JFSFA_OTAJFS_TASK_PRIORITY  10
#define LED_MONITOR_CHASE_PRIORITY 2
#define LED_MONITOR_BLINK_PRIORITY 2
#define NTP_CONNECT_TASK_PRIORITY 2
#define NTP_SYNC_CHECK_TASK_PRIORITY 8
#define PB_MON_UPDATE_TASK_PRIORITY 2
#define PB_MON_POLL_TASK_PRIORITY 2
#define RFSA_MON_TASK_PRIORITY   2
#define SMTP_SENDMAIL_TASK_PRIORITY 2
#define LED_SETSTATE_TASK_PRIORITY 2
#define SMTP_SENDFILE_TASK_PRIORITY 10  //5
#define DB_SYNC_CHECK_TASK_PRIORITY 2
#define POST_DEBUG_LOG_SERVER_PRIORITY 2
#define GET_RECORD_SYNCSTATUS_PRIORITY 2
#define SEND_RECORDLOG_SERVER_PRIORITY 2
#define TCPAC_MON_TASK_PRIORITY  2
#define TCPAC_ClientListen_TASK_PRIORITY  4
#define POST_REC_LOG_SERVER_PRIORITY 2
#define UART0_EVENT_TASK_PRIORITY 3
#define START_WEBSERVER_TASK_PRIORITY 2
#define WIFI_NETWORKSCAN_TASK_PRIORITY 2
#define WIFI_SCANTASK_PRIORITY 2

#define BLE_TASK_PRIORITY 2
#define BLE_SUBTASK_PRIORITY 2
#define CONSOLE_TASK_PRIORITY 5
#define CONSOLE_INIT_TASK_PRIORITY 5
#define ETH_TASK_PRIORITY 2
#define EVENT_TASK_PRIORITY 2
#define EVENT_CHECK_TASK_PRIORITY 6	//3
#define UPDATE_SCH_TABLE_PRIORITY 2
#define UPDATE_ACT_TABLE_TASK_PRIORITY 2
#define EVENT_EXECUTE_TASK_PRIORITY 8	//5
#define HTTP_TASK_PRIORITY 2
#define HTTP_FETCH_TASK_PRIORITY 2
#define HTTP_FILE_TASK_PRIORITY 5
#define IDLE_TASK_PRIORITY 2
#define IHUB_TASK_PRIORITY 2
#define IHUB_WDT_TASK_PRIORITY 2
#define democonfigDEMO_PRIORITY 3
#define LED_TASK_PRIORITY 2
#define CHECK_INPUT_TASK_PRIORITY 2
#define LED_UPDATE_BLINKSTATE_PRIORITY 2
#define NTP_TASK_PRIORITY 2
#define PBUTTON_TASK_PRIORITY 2
#define SMTP_TASK_PRIORITY 2
#define SPIFFS_MONITOR_TASK_PRIORITY 2
#define SYSTEM_TASK_PRIORITY 2
#define Auto_Execute_TASK_PRIORITY 2
#define DA_TASK_PRIORITY 2
#define SRV_CONN_TASK_PRIORITY 2
#define MON_SERVER_TASK_PRIORITY 2
#define SPIFFS_READ_TASK_PRIORITY 2
#define POST_FILE_ACK_TASK_PRIORITY 2
#define SYSTEM_STATE_TASK_PRIORITY 2
#define SYSTEM_TIMER_TASK_PRIORITY 2
#define TCP_TASK_PRIORITY 2
#define TCP_SOCKET1_TASK_PRIORITY 2
#define TCP_SOCKET2_TASK_PRIORITY 2
#define TCP_SOCKET3_TASK_PRIORITY 2
#define TCP_SOCKET4_TASK_PRIORITY 2
#define TRIM_TASK_PRIORITY 2
#define TRIM_SUBTASK_PRIORITY 9
#define READ_COLOR_TABLE_TASK_PRIORITY 5
#define READ_COMMAND_TABLE_TASK_PRIORITY 5
#define READ_PLAYLIST_TABLE_TASK_PRIORITY 5
#define SQL_TASK_PRIORITY 2
#define UART_TASK_PRIORITY 2
#define UDP_TASK_PRIORITY 2
#define UDP_SOCKET_TASK_PRIORITY 2
#define WEBSERVER_TASK_PRIORITY 2
#define WIFI_TASK_PRIORITY 2
#define FMA_CPY_ALLFILES_TASK_PRIORITY 2
#define WATCHDOG_TASK_PRIORITY 0

//1
#define COLOR_TABLE_QUE_LENGTH 1000
#define READ_SQL_TABLE_QUEUE_DEPTH 60
#define READ_SQL_TABLE_V_QUEUE_DEPTH 15
#define READ_SQL_TABLE_QUEUE_ENTRY_SIZE 1000
//#define PLAYLIST_TABLE_QUE_LENGTH 1000

#define HTTP_FETCH_QUE_LENGTH 200
#define HTTP_POST_QUE_LENGTH 100
#define BLEA_RD_SYS_PROP_TASK_QUEUE_LENGTH  2
#define BLEA_RD_WIFI_SCANLIST_TASK_QUEUE_LENGTH  2
#define CONSOLE_DEV_INFO_TASK_QUEUE_LENGTH  6	//2
#define FILE_SMTP_READ_TASK_QUEUE_LENGTH  5
#define CONSOLE_MSG_DBG_TASK_QUEUE_LENGTH  200
#define DIRECT_METHOD_RES_TASK_QUEUE_LENGTH  10
//#define COA_PROC_UART_MON_TASK_QUEUE_LENGTH  2
//#define COA_UART_EVENT_TASK_QUEUE_LENGTH  2
//#define COA_JFS_READ_FOTA_TASK_QUEUE_LENGTH  2
//#define COUA_PROC_UART_MON_TASK_QUEUE_LENGTH  2
//#define COUA_UART2_EVENT_TASK_QUEUE_LENGTH  2
//#define COUA_JFS_READ_FOTA_TASK_QUEUE_LENGTH  2
#define FILE_MANAGER_RX_OBJ_QUE_COUNT 500
#define EA_MON_TASK_TX_QUEUE_LENGTH  2
#define EA_MON_TASK_RX_QUEUE_LENGTH  2
//#define FMA_JFSSMTP_READ_TASK_QUEUE_LENGTH  2
//#define FMA_SDSMTP_READ_TASK_QUEUE_LENGTH  2
//#define FMA_RD_LOG_DATA_TASK_QUEUE_LENGTH  2
#define FS_MON_TASK_QUEUE_LENGTH  2
//#define HA_HTTP_STR_READER_TASK_QUEUE_LENGTH  2
#define HAQI4T_MON_TASK_QUEUE_LENGTH  5
//#define HAQI4T_GET_KEY_TASK_QUEUE_LENGTH  2
//#define HAQI4T_HTTP_STR_READER_TASK_QUEUE_LENGTH  2
//#define IA_STATS_TASK_QUEUE_LENGTH  2
//#define IV1_POLL_DATA_TASK_QUEUE_LENGTH  2
//#define I_POLL_DATA_TASK_QUEUE_LENGTH  2
//#define JFSFA_OTAJFS_TASK_QUEUE_LENGTH  2
#define RFSA_MON_TASK_RX_QUEUE_LENGTH  2
#define RFSA_MON_TASK_TX_QUEUE_LENGTH  2
#define SQL_TASK_QUEUE_LENGTH  300
#define POST_DEBUG_LOG_SERVER_QUEUE_LENGTH  3
#define GET_RECORD_SYNCSTATUS_QUEUE_LENGTH  3
#define Record_Sync_New_Que_COUNT           3
#define Record_Sync_Que_COUNT           	3
#define SPIFFS_QUE_COUNT           			2
#define Post_File_Ack_QUE_COUNT           	2
#define ScriptExecute_Ack_QUE_COUNT         100

#define TCPAC_MON_TASK_TX_QUEUE_LENGTH  2
#define TCPAC_MON_TASK_RX_QUEUE_LENGTH  2

#define WIFI_NETWORKSCAN_QUEUE_LENGTH 2
#define PROCESS_TWIN_QUEUE_LENGTH 10  //3
#define PROCESS_TWIN_COMMAND_QUEUE_LENGTH 5
#define IHUB_CONNECT_QUEUE_LENGTH 3
#define NTP_RX_QUEUE_LENGTH 5
#define PB_RX_QUEUE_LENGTH 20
#define PB_Post_QUEUE_LENGTH 5
#define PB_gpio_evt_queue_LENGTH	30
#define CheckInput_gpio_evt_queue_LENGTH	30

#define SMTP_OBJ_QUE_COUNT 30
#define SMTP_MAIL_QUE_COUNT 10
#define UPLOAD_FILE_QUE_COUNT 10
//#define GET_PROP_QUEUE_LENGTH 3
#define ADDMAILREQTOQUEUE_LENGTH 10
#define SETSTATEREQTOQUEUE_LENGTH 20
#define FMA_CPYALLFILES_QUE_COUNT 5

#define DIRECT_METHOD_RES_TASK_QUEUE_ITEMSIZE   4096
#define BLEA_RD_SYS_PROP_TASK_QUEUE_ITEMSIZE	400
#define BLEA_RD_WIFI_SCANLIST_TASK_QUEUE_ITEMSIZE 400
#define FILE_SMTP_READ_TASK_QUEUE_ITEMSIZE 100
#define CONSOLE_DEV_INFO_TASK_QUEUE_ITEMSIZE 500
#define PUSH_POST_INFO_TASK_QUEUE_ITEMSIZE 500
#define PB_gpio_evt_queue_ITEMSIZE 	sizeof(uint32_t)
#define CheckInput_gpio_evt_queue_ITEMSIZE 	sizeof(uint32_t)

#define PROCESS_TWIN_QUEUE_ITEMSIZE	1024    //500
#define PROCESS_TWIN_COMMAND_QUEUE_ITEMSIZE	8192
#define IHUB_CONNECT_QUEUE_ITEMSIZE	512
#define SMTP_MAIL_QUE_COUNT_ITEMSIZE	2500
#define UPLOAD_FILE_QUE_COUNT_ITEMSIZE	2500
#define POST_DEBUG_LOG_SERVER_QUEUE_ITEMSIZE	2500
#define GET_RECORD_SYNCSTATUS_QUEUE_ITEMSIZE	2000
#define Record_Sync_Que_COUNT_ITEMSIZE	500
#define Record_Sync_New_Que_COUNT_ITEMSIZE	4096
#define WIFI_NETWORKSCAN_QUEUE_ITEMSIZE 100
#define ExecuteScript_QUEUE_ITEMSIZE 2048
#define Post_File_Ack_QUEUE_ITEMSIZE 400
#define SPIFFS_QUE_ITEMSIZE          		2200
#define FMA_CPYALLFILES_QUEUE_ITEMSIZE 500
#define LED_SETSTATE_QUEUE_ITEMSIZE 100
//2

#endif /* MAIN_CONFIG_H_ */
